name: run e2e test of main branches

on: 
  push:
    branches:
      'main'
      
jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: run e2e tests
        run: npm cypress run --spec 'cypress/e2e/tests/**'
